# Generated by Django 4.2.5 on 2023-09-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предприятия')),
                ('division', models.CharField(choices=[('fuel', 'Топливный'), ('mech_engineering', 'Машиностроение'), ('nuclear', 'Ядерный оружейный комплекс'), ('energy', 'Энергетический')], default='fuel', max_length=100, verbose_name='Дивизион')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
            },
        ),
    ]
