# Generated by Django 4.2.5 on 2023-09-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='division',
            field=models.CharField(choices=[('Топливный', 'Топливный'), ('Машиностроение', 'Машиностроение'), ('Ядерный оружейный комплекс', 'Ядерный оружейный комплекс'), ('Энергетический', 'Энергетический')], default='fuel', max_length=100, verbose_name='Дивизион'),
        ),
    ]
