# Generated by Django 4.2.5 on 2023-09-20 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_alter_enterprise_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Дивизион',
                'verbose_name_plural': 'Дивизионы',
            },
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enterprise.division', verbose_name='Дивизион'),
        ),
    ]
